[project]
name = "agentic-nav"
version = "0.1.0"
description = "Conference navigation agent leveraging graph databases and semantic search to provide paper recommendations, research network exploration, and automated schedule generation for NeurIPS 2025 attendees."
readme = "README.md"
authors = [
    {name = "Shiqiang Wang", email = "s.wang9@exeter.ac.uk"},
    {name = "Herbert Woisetschläger", email = "herbert.woisetschlaeger@tum.de"}
]

requires-python = ">=3.10"
dependencies = [
    "aiofiles",
    "einops",
    "flask",
    "gradio[mcp,oauth]",
    "hatchling",
    "httpx",
    "kaleido",
    "litellm",
    "neo4j",
    "prompt-toolkit",
    "pydantic",
    "pydantic-settings",
    "pyvis>=0.3.2",
    "rich>=13.0.0",
    "sentence-transformers",
    "spaces>=0.44b3",
    "toon-format",
    "torch==2.8.0",
    "typer",
]

[tool.uv.workspace]
members = [
    "litellm",
]

[tool.uv.sources]
litellm = { git = "https://github.com/shiqiangw/litellm.git" }
toon-format = { git = "https://github.com/toon-format/toon-python.git" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.0.1",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
]

[tool.hatchling.build.targets.wheel]
packages = ["agentic_nav"]

[project.scripts]
agentic-nav-cli = "agentic_nav.frontend.cli:main"
agentic-nav-web = "agentic_nav.frontend.browser_ui:main"
